// Generated by dia2code
#ifndef STATE__CARD__H
#define STATE__CARD__H


#include "TypeCard.h"
#include "NumberCard.h"

namespace state {

  /// class Card - 
  class Card {
    // Associations
    // Attributes
  private:
    TypeCard typeOfCard;
    NumberCard numberOfCard;
    // Operations
  public:
    Card (NumberCard number, TypeCard type);
    NumberCard getNumberCard ();
    TypeCard getTypeCard ();
    ~Card ();
    // Setters and Getters
  };

};

#endif
