// Generated by dia2code
#ifndef STATE__CARDSDECK__H
#define STATE__CARDSDECK__H

#include <vector>

namespace state {
  class Card;
}

#include "Card.h"

namespace state {

  /// class CardsDeck - 
  class CardsDeck {
    // Associations
    // Attributes
  private:
    std::vector<Card> allCards;
    // Operations
  public:
    CardsDeck ();
    ~CardsDeck ();
    void distributeCards (std::vector<Player> players, int nbCards);
    void distributeCardsOnBoards (GameBoard& board,int nbCards);
    void shuffleDeck();
    // Setters and Getters
  };

};

#endif
