// Generated by dia2code
#ifndef STATE__COUNTSCORESTATE__H
#define STATE__COUNTSCORESTATE__H

#include <vector>
#include <memory>

namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  /// class CountScoreState - 
  class CountScoreState {
    // Operations
  public:
    CountScoreState ();
    ~CountScoreState ();
    void handleRequest (std::vector<std::unique_ptr<Player>> players);
    // Setters and Getters
  };

};

#endif
