// Generated by dia2code
#ifndef STATE__COUNTSCORESTATE__H
#define STATE__COUNTSCORESTATE__H

#include <vector>

namespace state {
  class Player;
  class State;
}

#include "Player.h"
#include "State.h"

namespace state {

  /// class CountScoreState - 
  class CountScoreState : public state::State {
    // Operations
  public:
    CountScoreState ();
    ~CountScoreState ();
    void handleRequest (std::vector<Player> players);
    // Setters and Getters
  };

};

#endif
