// Generated by dia2code
#ifndef STATE__DISTRIBUTECARDSTATE__H
#define STATE__DISTRIBUTECARDSTATE__H


namespace state {
  class State;
}

#include "State.h"

namespace state {

  /// class DistributeCardState - 
  class DistributeCardState : public state::State {
    // Operations
  public:
    DistributeCardState ();
    ~DistributeCardState ();
    void handleRequest ();
    // Setters and Getters
  };

};

#endif
