// Generated by dia2code
#ifndef STATE__DISTRIBUTECARDSTATE__H
#define STATE__DISTRIBUTECARDSTATE__H

#include <vector>
#include <memory>

namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  /// class DistributeCardState - 
  class DistributeCardState {
    // Operations
  public:
    DistributeCardState ();
    ~DistributeCardState ();
    void handleRequest (std::vector<std::unique_ptr<Player>> players);
    // Setters and Getters
  };

};

#endif
