// Generated by dia2code
#ifndef STATE__EXAMPLE__H
#define STATE__EXAMPLE__H


namespace state {

  /// class Example - 
  class Example {
    // Attributes
  public:
    int x     = 0;
    int y     = 0;
    // Operations
  public:
    void setX (int x);
    // Setters and Getters
  };

};

#endif
