// Generated by dia2code
#ifndef STATE__GAME__H
#define STATE__GAME__H

#include <vector>
#include <memory>

namespace state {
  class State;
  class Player;
}

#include "Player.h"

namespace state {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  private:
    int idGame;
    std::vector<std::unique_ptr<Player>> players;
    // Operations
  public:
    Game ();
    int getIdGame ();
    void setState (State * state);
    void request ();
    ~Game ();
    // Setters and Getters
  };

};

#endif
