// Generated by dia2code
#ifndef STATE__GAME__H
#define STATE__GAME__H

#include <vector>

namespace state {
  class Player;
  class State;
  class GameBoard;
}

#include "Player.h"
#include "GameBoard.h"

namespace state {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  private:
    std::vector<Player> players;
    static GameBoard * board;
    State *  state;
    // Operations
  public:
    Game ();
    void setState (State * state);
    void request ();
    void addPlayer (Player & player);
    void displayPlayers ();
    static GameBoard * getGameBoard ();
    ~Game ();
    // Setters and Getters
  };

};

#endif
