// Generated by dia2code
#ifndef STATE__INITSTATE__H
#define STATE__INITSTATE__H

#include <vector>

namespace state {
  class Player;
  class State;
}

#include "Player.h"
#include "State.h"

namespace state {

  /// class InitState - 
  class InitState : public state::State {
    // Operations
  public:
    InitState ();
    ~InitState ();
    void handleRequest (std::vector<Player> players);
    // Setters and Getters
  };

};

#endif
