// Generated by dia2code
#ifndef STATE__INITSTATE__H
#define STATE__INITSTATE__H


namespace state {
  class State;
}

#include "State.h"

namespace state {

  /// class InitState - 
  class InitState : public state::State {
    // Operations
  public:
    InitState ();
    ~InitState ();
    void handleRequest ();
    // Setters and Getters
  };

};

#endif
