// Generated by dia2code
#ifndef STATE__INITSTATE__H
#define STATE__INITSTATE__H

#include <vector>
#include <memory>

namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  /// class InitState - 
  class InitState {
    // Operations
  public:
    InitState ();
    ~InitState ();
    void handleRequest (std::vector<std::unique_ptr<Player>> players);
    // Setters and Getters
  };

};

#endif
