// Generated by dia2code
#ifndef STATE__NUMBERCARD__H
#define STATE__NUMBERCARD__H


namespace state {

  enum NumberCard {
    un     = 1,
    deux     = 2,
    trois     = 3,
    quatre     = 4,
    cinq     = 5,
    six     = 6,
    sept     = 7,
    dame     = 8,
    valet     = 9,
    roi     = 10
  };

};

#endif
