// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class Observer;
  class StateEvent;
  class State;
}

#include "Observer.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  public:
    std::vector<Observer*> observers;
    // Operations
  public:
    void registerObserver (Observer* observer);
    void notifyObserver (StateEvent& event, State* state);
    void const unregisterObserverver (Observer* o);
    void const unregisterObservers ( );
    // Setters and Getters
  };

};

#endif
