// Generated by dia2code
#ifndef STATE__OBSERVER__H
#define STATE__OBSERVER__H


namespace state {
  class StateEvent;
  class State;
}

namespace state {

  /// class Observer - 
  class Observer {
    // Operations
  public:
    void StateChanged (StateEvent& event, State& state);
    // Setters and Getters
  };

};

#endif
