// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H

#include <string>
#include <vector>

namespace state {
  class Card;
}

#include "Card.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    // Attributes
  private:
    std::string name;
    int totalScore;
    std::vector<Card> collectedCard;
    std::vector<Card> holdedCard;
    static int nbPlayerInstance;
    // Operations
  public:
    Player ();
    std::string getName ();
    void setName (std::string name);
    std::vector<Card> getCollectCard ();
    std::vector<Card> getHoldCard ();
    void play ();
    void displayHoldCard ();
    void displayCollectCard ();
    void addToScore (int points);
    int getScore ();
    void addHoldedCard (Card card);
    ~Player ();
    
  private:
    Card selectCardFromHand ();
    std::vector<Card> selectCardFromBoard ();
    void removeCardFromHand (Card card);
    // Setters and Getters
  };

};

#endif
