// Generated by dia2code
#ifndef STATE__PLAYERSTATUS__H
#define STATE__PLAYERSTATUS__H


namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  enum PlayerStatus {
    PLAYING,
    WON,
    LOST
  };

};

#endif
