// Generated by dia2code
#ifndef STATE__PLAYERSTATUS__H
#define STATE__PLAYERSTATUS__H


namespace state {

  enum PlayerStatus {
    PLAYING     = 1,
    WON     = 2,
    LOST     = 3
  };

};

#endif
