// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H


namespace render {
  class SceneData;
  class Scene;
}

#include "render/SceneData.h"
#include "render/Scene.h"

namespace State {

  /// class Player - 
  class Player {
    // Associations
    // Setters and Getters
  };

};

#endif
