// Generated by dia2code
#ifndef STATE__ROUNDSTATE__H
#define STATE__ROUNDSTATE__H

#include <vector>

namespace state {
  class Player;
  class State;
}

#include "Player.h"
#include "State.h"

namespace state {

  /// class RoundState - 
  class RoundState : public state::State {
    // Operations
  public:
    RoundState ();
    ~RoundState ();
    void handleRequest (std::vector<Player> & players);
    // Setters and Getters
  };

};

#endif
