// Generated by dia2code
#ifndef STATE__ROUNDSTATE__H
#define STATE__ROUNDSTATE__H

#include <vector>
#include <memory>

namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  /// class RoundState - 
  class RoundState {
    // Operations
  public:
    RoundState ();
    ~RoundState ();
    void handleRequest (std::vector<std::unique_ptr<Player>> players);
    // Setters and Getters
  };

};

#endif
