// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class Game;
}

#include "Game.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Operations
  public:
    State ();
    void handleRequest ();
    ~State ();
    // Setters and Getters
  };

};

#endif
