// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>
#include <string>

namespace state {
  class Player;
  class GameBoard;
  class CardsDeck;
}

#include "CardsDeck.h"
#include "GameBoard.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  public:
    int turn;
  private:
    std::vector<Player *> players;
    int nbPlayer;
    int maxScore;
    GameBoard* board;
    CardsDeck* allCards;
    // Operations
  public:
    State ();
    ~State ();
    int getMaxScore ();
    int getNbPlayer ();
    GameBoard * getBoard ();
    void setNbPlayer (int newNbPlayer);
    void setMaxScore (int newMaxScore);
    void initCards ();
<<<<<<< HEAD
    void initBoard();
    void addPlayer (std::string namePlayer);
    CardsDeck getAllCards ();
    std::vector<Player> getAllPlayers();
=======
    CardsDeck * getAllCards ();
>>>>>>> a78dea0f12b6d5629e9a90fbce536dc65459676d
    int incrementTurn ();
    void initBoard ();
    void addPlayer (std::string namePlayer);
    // Setters and Getters
  };

};

#endif
