// Generated by dia2code
#ifndef STATE__STATEEVENT__H
#define STATE__STATEEVENT__H


namespace state {
  class Observer;
}

#include "StateEventId.h"
#include "Observer.h"

namespace state {

  /// class StateEvent - 
  class StateEvent {
    // Associations
    // Attributes
  private:
    StateEventId stateEvent;
    // Operations
  public:
    StateEvent (StateEventId idEvent);
    StateEventId getStateEventId ();
    void setStateEventId (StateEventId id);
    // Setters and Getters
  };

};

#endif
