// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  enum StateEventId {
    SET_UP,
    DISTRIBUTE,
    CACUL_SCORE,
    PLAYER_THROW_CARD,
    PLAYER_CAPTURE_CARD
  };

};

#endif
