// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace render {
  class Scene;
}

#include "render/Scene.h"

namespace State {

  /// class State - 
  class State {
    // Associations
    // Setters and Getters
  };

};

#endif
