// Generated by dia2code
#ifndef STATE__TYPECARD__H
#define STATE__TYPECARD__H


namespace state {

  enum TypeCard {
    treffle     = 1,
    carreau     = 2,
    pique     = 3,
    coeur     = 4
  };

};

#endif
