// Generated by dia2code
#ifndef STATE__WAITSTATE__H
#define STATE__WAITSTATE__H

#include <vector>
#include <memory>

namespace state {
  class Player;
}

#include "Player.h"

namespace state {

  /// class WaitState - 
  class WaitState {
    // Operations
  public:
    WaitState ();
    ~WaitState ();
    void handleRequest (std::vector<std::unique_ptr<Player>> players);
    // Setters and Getters
  };

};

#endif
