// Generated by dia2code
#ifndef STATE__WAITSTATE__H
#define STATE__WAITSTATE__H


namespace state {
  class State;
}

#include "State.h"

namespace state {

  /// class WaitState - 
  class WaitState : public state::State {
    // Operations
  public:
    WaitState ();
    ~WaitState ();
    void handleRequest ();
    // Setters and Getters
  };

};

#endif
