// Generated by dia2code
#ifndef STATE__WAITSTATE__H
#define STATE__WAITSTATE__H

#include <vector>

namespace state {
  class Player;
  class State;
}

#include "Player.h"
#include "State.h"

namespace state {

  /// class WaitState - 
  class WaitState : public state::State {
    // Operations
  public:
    WaitState ();
    ~WaitState ();
    void handleRequest (std::vector<Player> & players);
    // Setters and Getters
  };

};

#endif
