// Generated by dia2code
#ifndef RENDER__SCENECOMPONENT__H
#define RENDER__SCENECOMPONENT__H


namespace render {

  enum SceneComponent {
    MENU,
    OPTION,
    PLAYER_A,
    PLAYER_B,
    PLAYER_C,
    PLAYER_D,
    SCORE_CALCULATION
  };

};

#endif
