// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H


namespace render {
  class SceneData;
}

#include "SceneComponent.h"
#include "SceneData.h"

namespace render {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  public:
    SceneComponent sceneElement;
    Sfml::RenderWindow window;
    state::Player playerInfo;
    SceneData sceneInfo;
    // Operations
  public:
    Scene ();
    ~Scene ();
    void init ();
    void drawScene ();
    // Setters and Getters
  };

};

#endif
