// Generated by dia2code
#ifndef RENDER__CARDPOSITION__H
#define RENDER__CARDPOSITION__H


namespace render {

  /// class CardPosition - 
  class CardPosition {
    // Attributes
  private:
    double x;
    double y;
    // Operations
  public:
    CardPosition ();
    ~CardPosition ();
    void changePos ();
    double getX ();
    double getY ();
    // Setters and Getters
  };

};

#endif
