// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <SFML/Graphics.hpp>

namespace sf {
  class RenderWindow;
};
namespace state {
  class Player;
};
namespace render {
  class SceneData;
};
namespace state {
  class Observer;
}

#include "SceneComponent.h"
#include "state/Player.h"
#include "SceneData.h"
#include "state/Observer.h"

namespace render {

  /// class Scene - 
  class Scene : public state::Observer {
    // Associations
    // Attributes
  public:
    SceneComponent sceneElement;
    sf::RenderWindow window;
    state::Player playerInfo;
    SceneData sceneInfo;
    // Operations
  public:
    Scene ();
    ~Scene ();
    void init ();
    void drawScene ();
    // Setters and Getters
  };

};

#endif
