// Generated by dia2code
#ifndef ENGINE__CAPTURECARD__H
#define ENGINE__CAPTURECARD__H

#include <vector>

namespace engine {
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class CaptureCard - 
  class CaptureCard : public engine::Command {
    // Attributes
  public:
    int indexCardHand;
    std::vector<int> indexsCardsBoard;
    // Operations
  public:
    CaptureCard ();
    ~CaptureCard ();
    bool execute (Engine* engine);
    bool validateCardHand ();
    bool validateCardBoard ();
    // Setters and Getters
  };

};

#endif
