// Generated by dia2code
#ifndef ENGINE__CMDTYPEID__H
#define ENGINE__CMDTYPEID__H


namespace engine {

  enum CMDTypeId {
    SETUP_GAME,
    FIRST_DISTRIBUTION,
    THROW_CARD,
    CAPTURE_CARD,
    DISTRIBUTE_CARD,
    COUNT_SCORE
  };

};

#endif
