// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

namespace engine {
  class Engine;
}

#include "CMDTypeId.h"
#include "Engine.h"
#include "TypeId.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    // Attributes
  private:
    CMDTypeId typeId;
    // Operations
  public:
    Command ();
    ~Command ();
    CMDTypeId getCMDTypeId ();
    void setNewCMD(CMDTypeId cmd);
    virtual bool execute (Engine* engine);
    // Setters and Getters
  };

};

#endif
