// Generated by dia2code
#ifndef ENGINE__COUNTSCORE__H
#define ENGINE__COUNTSCORE__H


namespace engine {
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class CountScore - 
  class CountScore : public engine::Command {
    // Operations
  public:
    CountScore ();
    ~CountScore ();
    bool execute (Engine * engine);
    // Setters and Getters
  };

};

#endif
