// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H


namespace state {
  class State;
};
namespace engine {
  class Command;
};
namespace state {
  class Player;
}

#include "state/State.h"
#include "Command.h"
#include "state/Player.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  private:
    state::State currentState;
    Command * actualCmd;
    // Operations
  public:
    Engine ();
    ~Engine ();
    void init ();
    state::Player& getActualPlayer ();
    state::State& getState ();
    void setNextPlayer ();
    Command getActualCommand ();
    void setActualCmd (Command* newCmd);
    // Setters and Getters
  };

};

#endif
