// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H


namespace state {
  class State;
};
namespace engine {
  class Command;
};
namespace state {
  class Player;
};
namespace engine {
  class Engine;
}

#include "state/State.h"
#include "state/Player.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  private:
    state::State  currentState;
    Command * actualCmd;
    // Operations
  public:
    Engine ();
    state::Player& getActualPlayer ();
    state::State& getState ();
    void setNextPlayer ();
    bool runCommand (Engine * e);
    Command* getActualCommand ();
    void setActualCmd (Command* newCmd);
    void setPlayerIndexForLastCapturedCard ();
    ~Engine ();
    // Setters and Getters
  };

};

#endif
