// Generated by dia2code
#ifndef ENGINE__ROUNDINITDISTRIBUTECARDS__H
#define ENGINE__ROUNDINITDISTRIBUTECARDS__H


namespace engine {
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class RoundInitDistributeCards - 
  class RoundInitDistributeCards : public engine::Command {
    // Operations
  public:
    RoundInitDistributeCards ();
    ~RoundInitDistributeCards ();
    bool execute (Engine * engine);
    // Setters and Getters
  };

};

#endif
