// Generated by dia2code
#ifndef ENGINE__ROUNDDISTRIBUTECARDS__H
#define ENGINE__ROUNDDISTRIBUTECARDS__H


namespace engine {
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class RoundDistributeCards - 
  class RoundDistributeCards : public engine::Command {
    // Operations
  public:
    RoundDistributeCards ();
    ~RoundDistributeCards ();
    bool execute (Engine * engine);
    // Setters and Getters
  };

};

#endif
