// Generated by dia2code
#ifndef ENGINE__SETUPGAME__H
#define ENGINE__SETUPGAME__H

#include <string>
#include <vector>

namespace engine {
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class SetUpGame - 
  class SetUpGame : public engine::Command {
    // Operations
  public:
    SetUpGame (int nbPlayer, int maxScore, std::vector<std::string> players);
    ~SetUpGame ();
    bool execute (Engine* engine);
    // Setters and Getters
  };

};

#endif
