// Generated by dia2code
#ifndef ENGINE__TYPEID__H
#define ENGINE__TYPEID__H


namespace engine {

  enum TypeId {
    SETUP_GAME,
    FIRST_DISTRIBUTION,
    THROW_CARD,
    CAPTURE_CARD,
    DISTRIBUTE_CARD,
    COUNT_SCORE
  };

};

#endif
