// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <string>
#include <vector>

namespace engine {
  class Engine;
  class ThrowCard;
  class CountScore;
  class CaptureCard;
  class RoundInitDistributeCards;
  class RoundDistributeCards;
  class SetUpGame;
}

#include "engine/Engine.h"
#include "ActionType.h"
#include "engine/ThrowCard.h"
#include "engine/CountScore.h"
#include "engine/CaptureCard.h"
#include "engine/RoundInitDistributeCards.h"
#include "engine/RoundDistributeCards.h"
#include "engine/SetUpGame.h"

namespace client {

  /// class Client - 
  class Client {
    // Attributes
  private:
    engine::Engine engine;
    // Operations
  public:
    Client ();
    void setUp ();
    void distributeCard ();
    bool initDistribute ();
    ActionType chooseAction ();
    void playThrowCard ();
    void playCaptureCard ();
    bool isEndOfGame ();
    char getValidatedChar (std::string prompt);
    int getValidatedInteger (std::string prompt);
    int getNbPlayerAndIA ();
    ~Client ();
  private:
    int enterNbPlayer ();
    int enterMaxScore ();
    std::vector<std::string> enterPlayersNames (int nbPlayers);
    int enterIndexToThrowedCard ();
    std::vector<int> enterIndexesToBeCollectedCards ();
    // Setters and Getters
  };

};

#endif
