// // Generated by dia2code
// #ifndef CLIENT__EXAMPLE__H
// #define CLIENT__EXAMPLE__H


// namespace client {

//   /// class Example - 
//   class Example {
//     // Attributes
//   public:
//     int x     = 0;
//     int y     = 0;
//     // Operations
//   public:
//     void setX (int x);
//     // Setters and Getters
//   };

// };

// #endif
