<<<<<<< HEAD
// Generated by dia2code
#ifndef CLIENT__EXAMPLE__H
#define CLIENT__EXAMPLE__H


namespace client {

  /// class Example - 
  class Example {
    // Attributes
  public:
    int x     = 0;
    int y     = 0;
    // Operations
  public:
    void setX (int x);
    // Setters and Getters
  };

};

#endif
=======
// // Generated by dia2code
// #ifndef CLIENT__EXAMPLE__H
// #define CLIENT__EXAMPLE__H


// namespace client {

//   /// class Example - 
//   class Example {
//     // Attributes
//   public:
//     int x     = 0;
//     int y     = 0;
//     // Operations
//   public:
//     void setX (int x);
//     // Setters and Getters
//   };

// };

// #endif
>>>>>>> bdd5ff2ba59388cfbd71939d7c9569d169584d6f
