// Generated by dia2code
#ifndef STATE__COUNTSCORESTATE__H
#define STATE__COUNTSCORESTATE__H


namespace state {
  class State;
}

#include "State.h"

namespace state {

  /// class CountScoreState - 
  class CountScoreState : public state::State {
    // Operations
  public:
    CountScoreState ();
    ~CountScoreState ();
    void handleRequest ();
    // Setters and Getters
  };

};

#endif
