// Generated by dia2code
#ifndef STATE__ROUNDSTATE__H
#define STATE__ROUNDSTATE__H


namespace state {
  class State;
}

#include "State.h"

namespace state {

  /// class RoundState - 
  class RoundState : public state::State {
    // Operations
  public:
    RoundState ();
    ~RoundState ();
    void handleRequest ();
    // Setters and Getters
  };

};

#endif
