// Generated by dia2code
#ifndef SF__RENDERWINDOW__H
#define SF__RENDERWINDOW__H


namespace render {
  class Scene;
}

#include "render/Scene.h"

namespace sf {

  /// class RenderWindow - 
  class RenderWindow {
    // Associations
    // Setters and Getters
  };

};

#endif
